# Site settings
title: twentyworld
SEOTitle: 夕豪 | twentyworld
header-img: img/post-bg-unix-linux.jpg
email: tyriontwenty@gmail.com
description: "all men must die, all men must serve"
keyword: "夕豪, twentyworld, Java, interview"
url: "http://twentyworld.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/twentyworld//twentyworld.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "all men must die, all men must serve"
sidebar-avatar: /img/self.png    # use absolute URL, seeing it's used in both `/` and `/about/`

# 分页
permalink: /:year/:month/:day/:title.html
paginate: 1
paginate_path: "article/:num"

# 转换
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--excerpt-->



# SNS settings
RSS: false
# weibo_username:     twentyworld
zhihu_username:     oven-lee
github_username:    twentyworld
jianshu_username:   f7cc168c1716
#twitter_username:   twentyworld




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: twentyworld

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b88999296d359de92c81                            #生成的clientID
  clientSecret: d51dfef86c3d3bd2e2485518f2f3b99a404ce020    #生成的clientSecret
  repo: twentyworld.github.io    #仓库名称
  owner: twentyworld    #github用户名
  admin: twentyworld
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0c084e0d8331443cbf0269f04c0da676

# # Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: twentyworld.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
